osx_image: xcode8.1
language: objective-c
script:
- set -o pipefail && xcodebuild build -project yalu102.xcodeproj -xcconfig yalu102.xcconfig -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
