#!/bin/sh
ls /etc/rc.d | while read a; do /etc/rc.d/$a; done
sleep 1
launchctl unload $(ls /System/Library/LaunchDaemons/ | grep -v logd | grep -v ReportCrash | while read a; do printf /System/Library/LaunchDaemons/$a\ ; done)
launchctl unload /System/Library/NanoLaunchDaemons
sleep 1
launchctl load /Library/LaunchDaemons
launchctl load /System/Library/LaunchDaemons
launchctl load /System/Library/NanoLaunchDaemons

exit 0
